### ISSUE TITLE
zip() creates zip object in python 3 and list object in python 2...leads to TypeError

### ISSUE THREAD

**Issue by SanFranciscoSunrise** [aldryn/aldryn-client#139]
For some reason whenever I build aldryn-client it builds under the python3.4 environment.  As such the code has been running under the 3.4 environment and I managed to find a small bug in utils.py

In utils.py the function "pretty_size(num)" utilizes a global object "unit_list" that is created as shown below:

unit_list = zip(
        ['bytes', 'kB', 'MB', 'GB', 'TB', 'PB'],
        [0, 0, 1, 2, 2, 2],
)

The problem is that in python2 unit_list automatically becomes a list object and in python3 it remains a zip object.  So when "len(unit_list)" is called within "def  pretty_size(num)" on line 172 of utils.py:

172:    exponent = min(int(log(num, 1024)), len(unit_list) - 1)

we get a TypeError under the python3 environment, zip objects have no len().  I solved this in my own copy by simply creating the list object with list() when unit_list is created globally, as shown below:

unit_list = list(zip(
        ['bytes', 'kB', 'MB', 'GB', 'TB', 'PB'],
        [0, 0, 1, 2, 2, 2],
))

I'm not sure if this is the best way to solve this or even globally appropriate but it seems to have worked for me for now.

Separately can someone email me as to why when I run ./scripts/build_unix it buils with the python3.4 environment?  Is this just how it is?  or can I change something to force python2.7?  My email address is BensThoughts@GMail.com and an answer would be greatly appreciated.

**Comment by Chive** [comment]
PR #140 has been merged.

> Separately can someone email me as to why when I run ./scripts/build_unix it buils with the python3.4 environment? Is this just how it is?

The build script uses your default python version - see this line https://github.com/aldryn/aldryn-client/blob/master/scripts/build-unix#L11

You can change it to e.g.

```
# create new venv
virtualenv -p `which python2.7` $VENV
```
to run the build process in a specific version.

Best,
Kim
