### ISSUE TITLE
Greeting fails after login

### ISSUE THREAD

**Issue by benzkji** [aldryn/aldryn-client#150]
Epic

    File "/usr/local/lib/python2.7/site-packages/aldryn_client/cloud.py", line 83, in login
    greeting = '{} {} ({})'.format(first_name, last_name, email)
        UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 2: ordinal not in range(128)

don't know if this is a shell issue, though ;-) I got zsh / Oh my zsh.

**Comment by Chive** [comment]
Hi @benzkji, thanks for reporting - this is indeed an issue. It'll be fixed in the PR #151 / the next released version.
