### ISSUE TITLE
[suggestion] implement argcomplete

### ISSUE THREAD

**Issue by petrklus** [aldryn/aldryn-client#159]
Hello!

A minor suggestion - would be nice to have tab-completion in bash (and possibly other shells).

(something like [this](https://argcomplete.readthedocs.io/en/latest/#activating-global-completion%20argcomplete))

**Comment by Chive** [comment]
Hi @petrklus 

You can install tab completion for bash and zsh (and possibly others) by adding this command to your config file (``.bashrc`` / ``.zshrc``):

```bash
eval "$(_ALDRYN_COMPLETE=source aldryn)"
```

Best,
Kim
