### ISSUE TITLE
add-on validation JSON parsing issues

### ISSUE THREAD

**Issue by techdragon** [aldryn/aldryn-client#35]
The JSON parser that checks the JSON file when validating an add-on, does not handle ```//``` comments in a JSON file.

This happens when you try to validate an add-on with a comment in the JSON.
````
$ ~ aldryn addon validate
control.aldryn.com
ValueError('No JSON object could be decoded',)
````
And this is what happens after you remove the comment.
````
$ ~ aldryn addon validate
control.aldryn.com
Configuration file is valid
````

**Comment by Chive** [comment]
Hello @techdragon 

Comments were removed from JSON by design. You can however - add your comments and minify it before running ``aldryn addon validate``.

Read more about this here:
> I removed comments from JSON because I saw people were using them to hold parsing directives, a practice which would have destroyed interoperability. I know that the lack of comments makes some people sad, but it shouldn't. 

> Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like. Then pipe it through JSMin before handing it to your JSON parser.﻿

Source: https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr
