### ISSUE TITLE
Changing network (or network DNS) breaks connection to docker.io 

### ISSUE THREAD

**Issue by evildmp** [aldryn/aldryn-client#78]
This morning I was able to run ``aldryn project workon`` for a project at home; when moved to my office later in the day I would consistently get an error 

```Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/postgres/images. You may want to check your internet connection or if you are behind a proxy.```

After finally deleting and recreating the Virtual Box VM, it worked again. Then on returning home, it failed with the same error, until I once more deleted and recreated the VM.

@GaretJax speculated this may be due to different network/DNS addresses at the two locations.

If this is the case, then the Docker configuration needs to be robust enough to handle this.

**Comment by Chive** [comment]
@evildmp Nothing we can do there since we don't configure the user's shell nor system. However we do now provide many helpers in ``aldryn doctor`` which helps tackling those issues. Closing here.
